//! Provenance-preserving scalar-field normal observation semantics.
//!
//! Normal observations lower to the shared solver-neutral problem IR. Each
//! generated scalar relation receives one caller-owned provenance value so
//! stable observation identifiers remain unique after a vector observation is
//! expanded. The order is exposed through [`NormalConstraintRole`].
//!
//! Direction-only and axial modes impose only an orthonormal-complement
//! equality. They never invent a nonzero gradient magnitude. Oriented modes
//! use an explicit nonnegative minimum projection, and angular cones accept
//! only the convex domain from zero (inclusive) to a right angle (exclusive).
//! D=3 multi-row complement semantics accept soft squared L2 loss only;
//! componentwise L1 and Huber losses are rejected because they depend on the
//! arbitrary orthonormal-complement basis.
//!
//! Normal observations are available only in one, two, or three dimensions:
//!
//! ```compile_fail
//! use georbf::NormalObservation;
//!
//! let _ = std::mem::size_of::<NormalObservation<4>>();
//! ```

use std::error::Error;
use std::fmt;

use crate::diagnostics::{DiagnosticPath, DiagnosticPathError};
use crate::dimension::{Dim, SupportedDimension};
use crate::functional::{
    FunctionalAtom, FunctionalError, FunctionalExpr, FunctionalProvenance, FunctionalTerm,
    ObservationFunctional,
};
use crate::geometry::{GeometryError, Point, UnitDirection, Vector};
use crate::problem_ir::{
    Enforcement, ProblemIrError, SemanticConstraint, SemanticExpression, SemanticProvenance,
    SemanticRelation, SoftLoss,
};
use crate::units::AngleUnit;

/// The five supported normal-observation modes.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum NormalMode {
    /// All Cartesian gradient components are prescribed exactly.
    GradientVector,
    /// Only parallelism with a direction is prescribed.
    DirectionOnly,
    /// Parallelism and an explicitly oriented minimum projection are prescribed.
    DirectionWithPolarity,
    /// A convex angular tolerance and minimum oriented projection are prescribed.
    AngularCone,
    /// An unoriented axis is prescribed, invariant under sign reversal.
    AxialDirection,
}

/// Deterministic role of one scalar relation generated by a normal observation.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum NormalConstraintRole {
    /// Exact Cartesian gradient component at the zero-based axis.
    GradientComponent(usize),
    /// Exact zero projection onto one orthonormal-complement basis vector.
    OrthogonalComplement(usize),
    /// Oriented lower bound on the projection along the supplied normal.
    PolarProjection,
    /// Ordered Lorentz-cone angular relation.
    AngularCone,
}

/// Explicit same-unit policy for reviewing whether a fitted gradient is near zero.
#[derive(Clone, Copy, Debug, PartialEq)]
#[must_use]
pub struct GradientMagnitudePolicy {
    reference_scale: f64,
    relative_threshold: f64,
    absolute_threshold: f64,
}

impl GradientMagnitudePolicy {
    /// Constructs an explicit magnitude policy.
    ///
    /// `reference_scale` has the same units as the gradient magnitude and must
    /// be positive. `relative_threshold` is dimensionless and nonnegative.
    ///
    /// # Errors
    ///
    /// Rejects non-finite or out-of-domain values and a product that overflows.
    pub fn try_new(
        reference_scale: f64,
        relative_threshold: f64,
    ) -> Result<Self, NormalObservationError> {
        if !reference_scale.is_finite() || reference_scale <= 0.0 {
            return Err(NormalObservationError::InvalidGradientReferenceScale {
                value: reference_scale,
            });
        }
        if !relative_threshold.is_finite() || relative_threshold < 0.0 {
            return Err(NormalObservationError::InvalidRelativeGradientThreshold {
                value: relative_threshold,
            });
        }
        let absolute_threshold = reference_scale * relative_threshold;
        if !absolute_threshold.is_finite() {
            return Err(NormalObservationError::GradientThresholdOverflow {
                reference_scale,
                relative_threshold,
            });
        }
        Ok(Self {
            reference_scale,
            relative_threshold,
            absolute_threshold,
        })
    }

    /// Returns the positive reference scale in gradient units.
    #[must_use]
    pub const fn reference_scale(self) -> f64 {
        self.reference_scale
    }

    /// Returns the nonnegative dimensionless threshold.
    #[must_use]
    pub const fn relative_threshold(self) -> f64 {
        self.relative_threshold
    }

    /// Returns the resulting nonnegative threshold in gradient units.
    #[must_use]
    pub const fn absolute_threshold(self) -> f64 {
        self.absolute_threshold
    }
}

/// Source-aware review of one fitted gradient magnitude.
#[derive(Clone, Debug, PartialEq)]
#[must_use]
pub struct NormalGradientDiagnostics {
    source: DiagnosticPath,
    magnitude: f64,
    policy: GradientMagnitudePolicy,
    near_zero: bool,
}

impl NormalGradientDiagnostics {
    /// Borrows the complete diagnostic path and stable observation identifier.
    pub const fn source(&self) -> &DiagnosticPath {
        &self.source
    }

    /// Returns the overflow-safe Euclidean gradient magnitude.
    #[must_use]
    pub const fn magnitude(&self) -> f64 {
        self.magnitude
    }

    /// Returns the caller-selected comparison policy.
    pub const fn policy(&self) -> GradientMagnitudePolicy {
        self.policy
    }

    /// Reports whether `magnitude <= absolute_threshold`.
    #[must_use]
    pub const fn is_near_zero(&self) -> bool {
        self.near_zero
    }
}

/// One validated normal observation lowered to scalar semantic relations.
#[derive(Clone, Debug, PartialEq)]
#[must_use]
pub struct NormalObservation<const D: usize>
where
    Dim<D>: SupportedDimension,
{
    mode: NormalMode,
    roles: Vec<NormalConstraintRole>,
    constraints: Vec<SemanticConstraint<D>>,
}

impl<const D: usize> NormalObservation<D>
where
    Dim<D>: SupportedDimension,
{
    /// Constructs exact Cartesian gradient-component equalities.
    ///
    /// Provenances are consumed in axis order and exactly `D` are required.
    ///
    /// # Errors
    ///
    /// Rejects a provenance count mismatch, duplicate identifier, allocation
    /// failure, or shared functional/IR validation failure.
    pub fn try_gradient_vector(
        provenances: impl IntoIterator<Item = SemanticProvenance>,
        point: Point<D>,
        gradient: Vector<D>,
        enforcement: Enforcement,
    ) -> Result<Self, NormalObservationError> {
        let provenances = collect_provenances(provenances, D)?;
        validate_enforcement(enforcement)?;
        let mut roles = reserve(D, NormalObservationStorage::Roles)?;
        let mut constraints = reserve(D, NormalObservationStorage::Constraints)?;
        for (axis, (provenance, target)) in provenances
            .into_iter()
            .zip(gradient.into_components())
            .enumerate()
        {
            let direction = coordinate_direction(axis)?;
            let expression = derivative_expression(point, direction, &provenance, 1.0)?;
            constraints.push(SemanticConstraint::try_new(
                provenance,
                SemanticRelation::Equality { expression, target },
                enforcement,
            )?);
            roles.push(NormalConstraintRole::GradientComponent(axis));
        }
        Ok(Self {
            mode: NormalMode::GradientVector,
            roles,
            constraints,
        })
    }

    /// Constructs sign-insensitive direction-only complement equalities.
    ///
    /// Provenances are consumed in complement-basis order and exactly `D - 1`
    /// are required. This mode is rejected in D=1 because it would add no row.
    ///
    /// # Errors
    ///
    /// Rejects D=1, a provenance count mismatch or duplicate, invalid soft
    /// enforcement, componentwise L1 or Huber loss in D=3, allocation failure,
    /// or shared functional/IR failure.
    pub fn try_direction_only(
        provenances: impl IntoIterator<Item = SemanticProvenance>,
        point: Point<D>,
        normal: UnitDirection<D>,
        enforcement: Enforcement,
    ) -> Result<Self, NormalObservationError> {
        Self::try_complement_mode(
            NormalMode::DirectionOnly,
            provenances,
            point,
            normal,
            enforcement,
        )
    }

    /// Constructs complement equalities plus `n^T grad f >= minimum_gradient`.
    ///
    /// Provenances are consumed for the `D - 1` complement rows followed by
    /// the polar-projection bound, so exactly `D` are required. A zero minimum
    /// is accepted only because the caller supplied it explicitly.
    ///
    /// # Errors
    ///
    /// Rejects a negative or non-finite minimum, provenance count mismatch or
    /// duplicate, invalid soft enforcement, componentwise L1 or Huber loss in
    /// D=3, allocation failure, or shared functional/IR failure.
    pub fn try_direction_with_polarity(
        provenances: impl IntoIterator<Item = SemanticProvenance>,
        point: Point<D>,
        normal: UnitDirection<D>,
        minimum_gradient: f64,
        enforcement: Enforcement,
    ) -> Result<Self, NormalObservationError> {
        validate_minimum_gradient(minimum_gradient)?;
        validate_complement_enforcement::<D>(NormalMode::DirectionWithPolarity, enforcement)?;
        let provenances = collect_provenances(provenances, D)?;
        let basis = complement_basis(normal)?;
        let mut roles = reserve(D, NormalObservationStorage::Roles)?;
        let mut constraints = reserve(D, NormalObservationStorage::Constraints)?;
        let mut provenance_iter = provenances.into_iter();
        for (index, direction) in basis.into_iter().enumerate() {
            let provenance = next_provenance(&mut provenance_iter)?;
            constraints.push(equality_constraint(
                provenance,
                point,
                direction,
                0.0,
                enforcement,
            )?);
            roles.push(NormalConstraintRole::OrthogonalComplement(index));
        }
        let provenance = next_provenance(&mut provenance_iter)?;
        constraints.push(lower_bound_constraint(
            provenance,
            point,
            normal,
            minimum_gradient,
            enforcement,
        )?);
        roles.push(NormalConstraintRole::PolarProjection);
        Ok(Self {
            mode: NormalMode::DirectionWithPolarity,
            roles,
            constraints,
        })
    }

    /// Constructs a convex angular cone and an explicit polar-projection bound.
    ///
    /// Exactly two provenances are required: cone first, projection bound
    /// second. `angle` is interpreted in the supplied unit and must satisfy
    /// `0 <= angle < pi/2`. This mode is rejected in D=1 because its cone would
    /// be independent of the angle.
    ///
    /// # Errors
    ///
    /// Rejects D=1, an invalid or unrepresentable angle, an invalid minimum,
    /// provenance count mismatch or duplicate, invalid soft enforcement,
    /// allocation failure, or shared functional/IR failure.
    pub fn try_angular_cone(
        provenances: impl IntoIterator<Item = SemanticProvenance>,
        point: Point<D>,
        normal: UnitDirection<D>,
        angle: f64,
        angle_unit: AngleUnit,
        minimum_gradient: f64,
        enforcement: Enforcement,
    ) -> Result<Self, NormalObservationError> {
        if D == 1 {
            return Err(NormalObservationError::UnsupportedModeInOneDimension {
                mode: NormalMode::AngularCone,
            });
        }
        let angle_radians = validate_angle(angle, angle_unit)?;
        validate_minimum_gradient(minimum_gradient)?;
        validate_enforcement(enforcement)?;
        let slope = angle_radians.tan();
        if !slope.is_finite() || slope < 0.0 {
            return Err(NormalObservationError::AngularConeSlopeOverflow { angle_radians });
        }
        if angle > 0.0 && (angle_radians == 0.0 || slope == 0.0) {
            return Err(NormalObservationError::AngularConeAngleNotRepresentable {
                value: angle,
                unit: angle_unit,
            });
        }
        let provenances = collect_provenances(provenances, 2)?;
        let basis = complement_basis(normal)?;
        let mut provenance_iter = provenances.into_iter();
        let cone_provenance = next_provenance(&mut provenance_iter)?;
        let mut lhs = reserve(basis.len(), NormalObservationStorage::ConeLhs)?;
        for direction in basis {
            lhs.push(derivative_expression(
                point,
                direction,
                &cone_provenance,
                1.0,
            )?);
        }
        let rhs = derivative_expression(point, normal, &cone_provenance, slope)?;
        let cone = SemanticConstraint::try_new(
            cone_provenance,
            SemanticRelation::SecondOrderCone { lhs, rhs },
            enforcement,
        )?;
        let projection_provenance = next_provenance(&mut provenance_iter)?;
        let projection = lower_bound_constraint(
            projection_provenance,
            point,
            normal,
            minimum_gradient,
            enforcement,
        )?;
        let mut roles = reserve(2, NormalObservationStorage::Roles)?;
        roles.push(NormalConstraintRole::AngularCone);
        roles.push(NormalConstraintRole::PolarProjection);
        let mut constraints = reserve(2, NormalObservationStorage::Constraints)?;
        constraints.push(cone);
        constraints.push(projection);
        Ok(Self {
            mode: NormalMode::AngularCone,
            roles,
            constraints,
        })
    }

    /// Constructs axial, sign-invariant complement equalities.
    ///
    /// Provenances are consumed in complement-basis order and exactly `D - 1`
    /// are required. D=1 is rejected because the mode would add no constraint.
    ///
    /// # Errors
    ///
    /// Rejects D=1, a provenance count mismatch or duplicate, invalid soft
    /// enforcement, componentwise L1 or Huber loss in D=3, allocation failure,
    /// or shared functional/IR failure.
    pub fn try_axial_direction(
        provenances: impl IntoIterator<Item = SemanticProvenance>,
        point: Point<D>,
        axis: UnitDirection<D>,
        enforcement: Enforcement,
    ) -> Result<Self, NormalObservationError> {
        Self::try_complement_mode(
            NormalMode::AxialDirection,
            provenances,
            point,
            axis,
            enforcement,
        )
    }

    fn try_complement_mode(
        mode: NormalMode,
        provenances: impl IntoIterator<Item = SemanticProvenance>,
        point: Point<D>,
        normal: UnitDirection<D>,
        enforcement: Enforcement,
    ) -> Result<Self, NormalObservationError> {
        if D == 1 {
            return Err(NormalObservationError::UnsupportedModeInOneDimension { mode });
        }
        validate_complement_enforcement::<D>(mode, enforcement)?;
        let count = D - 1;
        let provenances = collect_provenances(provenances, count)?;
        let basis = complement_basis(normal)?;
        let mut roles = reserve(count, NormalObservationStorage::Roles)?;
        let mut constraints = reserve(count, NormalObservationStorage::Constraints)?;
        for (index, (provenance, direction)) in provenances.into_iter().zip(basis).enumerate() {
            constraints.push(equality_constraint(
                provenance,
                point,
                direction,
                0.0,
                enforcement,
            )?);
            roles.push(NormalConstraintRole::OrthogonalComplement(index));
        }
        Ok(Self {
            mode,
            roles,
            constraints,
        })
    }

    /// Returns the high-level normal mode.
    #[must_use]
    pub const fn mode(&self) -> NormalMode {
        self.mode
    }

    /// Borrows scalar relation roles in deterministic provenance order.
    #[must_use]
    pub fn roles(&self) -> &[NormalConstraintRole] {
        &self.roles
    }

    /// Borrows lowered semantic constraints in deterministic role order.
    pub fn constraints(&self) -> &[SemanticConstraint<D>] {
        &self.constraints
    }

    /// Consumes the observation and returns its lowered semantic constraints.
    #[must_use]
    pub fn into_constraints(self) -> Vec<SemanticConstraint<D>> {
        self.constraints
    }

    /// Reviews one fitted gradient against an explicit same-unit policy.
    ///
    /// The first scalar relation supplies the source path. The result is a
    /// diagnostic only and never changes the observation or fitted field.
    ///
    /// # Errors
    ///
    /// Returns a fallible diagnostic-path copy error.
    pub fn try_review_gradient(
        &self,
        gradient: Vector<D>,
        policy: GradientMagnitudePolicy,
    ) -> Result<NormalGradientDiagnostics, NormalObservationError> {
        let provenance = self
            .constraints
            .first()
            .ok_or(NormalObservationError::InvalidInternalConstraintCount)?
            .provenance();
        let source = DiagnosticPath::try_observation(provenance)?;
        let magnitude = stable_norm(gradient.components());
        Ok(NormalGradientDiagnostics {
            source,
            magnitude,
            policy,
            near_zero: magnitude <= policy.absolute_threshold,
        })
    }
}

fn collect_provenances(
    provenances: impl IntoIterator<Item = SemanticProvenance>,
    expected: usize,
) -> Result<Vec<SemanticProvenance>, NormalObservationError> {
    let iterator = provenances.into_iter();
    let mut stored = reserve(expected, NormalObservationStorage::Provenances)?;
    for provenance in iterator {
        if stored.len() == expected {
            return Err(NormalObservationError::ProvenanceCountMismatch {
                expected,
                actual: stored.len().saturating_add(1),
            });
        }
        if stored.iter().any(|existing: &SemanticProvenance| {
            existing.observation_id() == provenance.observation_id()
        }) {
            return Err(NormalObservationError::DuplicateObservationId {
                identifier: provenance.observation_id().identifier(),
            });
        }
        stored.push(provenance);
    }
    if stored.len() != expected {
        return Err(NormalObservationError::ProvenanceCountMismatch {
            expected,
            actual: stored.len(),
        });
    }
    Ok(stored)
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum NormalObservationStorage {
    Provenances,
    ComplementBasis,
    ConeLhs,
    Roles,
    Constraints,
}

#[cfg(test)]
std::thread_local! {
    static FORCED_ALLOCATION_FAILURE: std::cell::Cell<Option<NormalObservationStorage>> =
        const { std::cell::Cell::new(None) };
}

fn reserve<T>(
    requested: usize,
    storage: NormalObservationStorage,
) -> Result<Vec<T>, NormalObservationError> {
    #[cfg(not(test))]
    let _ = storage;

    #[cfg(test)]
    if FORCED_ALLOCATION_FAILURE.with(|forced| {
        if forced.get() == Some(storage) {
            forced.set(None);
            true
        } else {
            false
        }
    }) {
        return Err(NormalObservationError::AllocationFailed { requested });
    }

    let mut values = Vec::new();
    values
        .try_reserve_exact(requested)
        .map_err(|_| NormalObservationError::AllocationFailed { requested })?;
    Ok(values)
}

fn next_provenance(
    provenances: &mut impl Iterator<Item = SemanticProvenance>,
) -> Result<SemanticProvenance, NormalObservationError> {
    provenances
        .next()
        .ok_or(NormalObservationError::InvalidInternalConstraintCount)
}

fn validate_enforcement(enforcement: Enforcement) -> Result<(), NormalObservationError> {
    enforcement.validate().map_err(NormalObservationError::Ir)
}

fn validate_complement_enforcement<const D: usize>(
    mode: NormalMode,
    enforcement: Enforcement,
) -> Result<(), NormalObservationError> {
    validate_enforcement(enforcement)?;
    if D == 3
        && let Enforcement::Soft { loss, .. } = enforcement
        && matches!(loss, SoftLoss::AbsoluteL1 | SoftLoss::Huber { .. })
    {
        return Err(NormalObservationError::UnsupportedComplementSoftLoss { mode, loss });
    }
    Ok(())
}

fn validate_minimum_gradient(value: f64) -> Result<(), NormalObservationError> {
    if value.is_finite() && value >= 0.0 {
        Ok(())
    } else {
        Err(NormalObservationError::InvalidMinimumGradient { value })
    }
}

fn validate_angle(value: f64, unit: AngleUnit) -> Result<f64, NormalObservationError> {
    let upper = match unit {
        AngleUnit::Radians => std::f64::consts::FRAC_PI_2,
        AngleUnit::Degrees => 90.0,
    };
    if !value.is_finite() || value < 0.0 || value >= upper {
        return Err(NormalObservationError::InvalidAngularConeAngle { value, unit });
    }
    let canonical = if value == 0.0 { 0.0 } else { value };
    Ok(match unit {
        AngleUnit::Radians => canonical,
        AngleUnit::Degrees => canonical.to_radians(),
    })
}

fn equality_constraint<const D: usize>(
    provenance: SemanticProvenance,
    point: Point<D>,
    direction: UnitDirection<D>,
    target: f64,
    enforcement: Enforcement,
) -> Result<SemanticConstraint<D>, NormalObservationError>
where
    Dim<D>: SupportedDimension,
{
    let expression = derivative_expression(point, direction, &provenance, 1.0)?;
    Ok(SemanticConstraint::try_new(
        provenance,
        SemanticRelation::Equality { expression, target },
        enforcement,
    )?)
}

fn lower_bound_constraint<const D: usize>(
    provenance: SemanticProvenance,
    point: Point<D>,
    direction: UnitDirection<D>,
    minimum: f64,
    enforcement: Enforcement,
) -> Result<SemanticConstraint<D>, NormalObservationError>
where
    Dim<D>: SupportedDimension,
{
    let expression = derivative_expression(point, direction, &provenance, 1.0)?;
    Ok(SemanticConstraint::try_new(
        provenance,
        SemanticRelation::LinearBound {
            expression,
            lower: Some(minimum),
            upper: None,
        },
        enforcement,
    )?)
}

fn derivative_expression<const D: usize>(
    point: Point<D>,
    direction: UnitDirection<D>,
    provenance: &SemanticProvenance,
    coefficient: f64,
) -> Result<SemanticExpression<D>, NormalObservationError>
where
    Dim<D>: SupportedDimension,
{
    let atom = FunctionalAtom::directional_derivative(
        point,
        direction,
        FunctionalProvenance::new(provenance.observation_id().identifier()),
    );
    let term = FunctionalTerm::try_new(coefficient, atom)?;
    let functional = ObservationFunctional::new(FunctionalExpr::try_new([term])?);
    Ok(SemanticExpression::try_new(functional, 0.0)?)
}

fn coordinate_direction<const D: usize>(
    axis: usize,
) -> Result<UnitDirection<D>, NormalObservationError>
where
    Dim<D>: SupportedDimension,
{
    let mut components = [0.0; D];
    let component = components
        .get_mut(axis)
        .ok_or(NormalObservationError::InvalidInternalConstraintCount)?;
    *component = 1.0;
    Ok(UnitDirection::try_new(components)?)
}

fn complement_basis<const D: usize>(
    normal: UnitDirection<D>,
) -> Result<Vec<UnitDirection<D>>, NormalObservationError>
where
    Dim<D>: SupportedDimension,
{
    let count = D.saturating_sub(1);
    let mut basis = reserve(count, NormalObservationStorage::ComplementBasis)?;
    if D == 1 {
        return Ok(basis);
    }
    let n = normal.components();
    let first_axis = n
        .iter()
        .enumerate()
        .min_by(|left, right| left.1.abs().total_cmp(&right.1.abs()))
        .map(|(axis, _)| axis)
        .ok_or(NormalObservationError::InvalidInternalConstraintCount)?;
    let mut first = [0.0; D];
    for axis in 0..D {
        first[axis] = f64::from(axis == first_axis) - n[first_axis] * n[axis];
    }
    let first = canonical_sign(UnitDirection::try_new(first)?)?;
    basis.push(first);
    if D == 3 {
        let first = first.components();
        let mut second = [0.0; D];
        second[0] = n[1] * first[2] - n[2] * first[1];
        second[1] = n[2] * first[0] - n[0] * first[2];
        second[2] = n[0] * first[1] - n[1] * first[0];
        basis.push(canonical_sign(UnitDirection::try_new(second)?)?);
    }
    if basis.len() != count {
        return Err(NormalObservationError::InvalidInternalConstraintCount);
    }
    Ok(basis)
}

fn canonical_sign<const D: usize>(
    direction: UnitDirection<D>,
) -> Result<UnitDirection<D>, NormalObservationError>
where
    Dim<D>: SupportedDimension,
{
    let components = direction.into_components();
    let reverse = components
        .iter()
        .copied()
        .find(|component| *component != 0.0)
        .is_some_and(f64::is_sign_negative);
    let canonical = if reverse {
        components.map(|component| -component)
    } else {
        components
    };
    Ok(UnitDirection::try_new(canonical)?)
}

fn stable_norm<const D: usize>(components: &[f64; D]) -> f64 {
    let scale = components
        .iter()
        .fold(0.0_f64, |current, value| current.max(value.abs()));
    if scale == 0.0 {
        return 0.0;
    }
    let scaled_square_sum = components
        .iter()
        .map(|value| (value / scale).powi(2))
        .sum::<f64>();
    scale * scaled_square_sum.sqrt()
}

/// Error returned while constructing or reviewing normal observations.
#[derive(Clone, Debug, PartialEq)]
#[non_exhaustive]
pub enum NormalObservationError {
    /// A mode would be vacuous or angle-insensitive in D=1.
    UnsupportedModeInOneDimension {
        /// Rejected mode.
        mode: NormalMode,
    },
    /// The supplied scalar-relation provenance count was not exact.
    ProvenanceCountMismatch {
        /// Required count.
        expected: usize,
        /// Supplied count, up to the first excess value.
        actual: usize,
    },
    /// Two generated scalar relations reused one stable observation identifier.
    DuplicateObservationId {
        /// Reused identifier.
        identifier: u64,
    },
    /// The oriented minimum gradient was negative or non-finite.
    InvalidMinimumGradient {
        /// Rejected value.
        value: f64,
    },
    /// An angular-cone angle was non-finite or outside its convex domain.
    InvalidAngularConeAngle {
        /// Rejected value in the supplied unit.
        value: f64,
        /// Supplied unit.
        unit: AngleUnit,
    },
    /// A positive valid-domain angle lost its positive value during conversion or tangent.
    AngularConeAngleNotRepresentable {
        /// Rejected value in the supplied unit.
        value: f64,
        /// Supplied unit.
        unit: AngleUnit,
    },
    /// A valid-domain angle produced a non-finite tangent slope.
    AngularConeSlopeOverflow {
        /// Converted radians.
        angle_radians: f64,
    },
    /// A componentwise soft loss would depend on a D=3 complement basis.
    UnsupportedComplementSoftLoss {
        /// Rejected complement-based mode.
        mode: NormalMode,
        /// Rejected componentwise loss.
        loss: SoftLoss,
    },
    /// A gradient reference scale was non-finite or not positive.
    InvalidGradientReferenceScale {
        /// Rejected value.
        value: f64,
    },
    /// A relative gradient threshold was negative or non-finite.
    InvalidRelativeGradientThreshold {
        /// Rejected value.
        value: f64,
    },
    /// Multiplying the explicit gradient scale and threshold overflowed.
    GradientThresholdOverflow {
        /// Supplied reference scale.
        reference_scale: f64,
        /// Supplied relative threshold.
        relative_threshold: f64,
    },
    /// Fallible vector reservation failed.
    AllocationFailed {
        /// Exact requested capacity.
        requested: usize,
    },
    /// An internal dimension/count invariant was not satisfied.
    InvalidInternalConstraintCount,
    /// Direction construction failed.
    Geometry(GeometryError),
    /// Atomic functional construction failed.
    Functional(FunctionalError),
    /// Shared semantic IR validation failed.
    Ir(ProblemIrError),
    /// A source-aware diagnostic path could not be copied.
    DiagnosticPath(DiagnosticPathError),
}

impl fmt::Display for NormalObservationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "invalid normal observation: {self:?}")
    }
}

impl Error for NormalObservationError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Geometry(source) => Some(source),
            Self::Functional(source) => Some(source),
            Self::Ir(source) => Some(source),
            Self::DiagnosticPath(source) => Some(source),
            _ => None,
        }
    }
}

impl From<GeometryError> for NormalObservationError {
    fn from(source: GeometryError) -> Self {
        Self::Geometry(source)
    }
}

impl From<FunctionalError> for NormalObservationError {
    fn from(source: FunctionalError) -> Self {
        Self::Functional(source)
    }
}

impl From<ProblemIrError> for NormalObservationError {
    fn from(source: ProblemIrError) -> Self {
        Self::Ir(source)
    }
}

impl From<DiagnosticPathError> for NormalObservationError {
    fn from(source: DiagnosticPathError) -> Self {
        Self::DiagnosticPath(source)
    }
}

#[cfg(test)]
mod tests {
    use std::num::NonZeroUsize;

    use super::*;
    use crate::problem_ir::{ObservationId, SourceLocation};

    type TestResult = Result<(), Box<dyn Error>>;

    struct ForcedAllocationFailure;

    impl ForcedAllocationFailure {
        fn new(storage: NormalObservationStorage) -> Self {
            FORCED_ALLOCATION_FAILURE.with(|forced| forced.set(Some(storage)));
            Self
        }
    }

    impl Drop for ForcedAllocationFailure {
        fn drop(&mut self) {
            FORCED_ALLOCATION_FAILURE.with(|forced| forced.set(None));
        }
    }

    fn provenance(identifier: u64) -> Result<SemanticProvenance, ProblemIrError> {
        SemanticProvenance::try_new(
            ObservationId::new(identifier),
            SourceLocation::try_new("tests/normal_observations.rs".to_owned(), NonZeroUsize::MIN)?,
            "gradient-unit".to_owned(),
            "fields.stratigraphy.normals".to_owned(),
            Some("normal".to_owned()),
        )
    }

    fn assert_angular_cone_allocation_failure(storage: NormalObservationStorage) -> TestResult {
        let provenances = [provenance(1)?, provenance(2)?];
        let point = Point::try_new([0.0, 0.0, 0.0])?;
        let normal = UnitDirection::try_new([0.0, 0.0, 1.0])?;
        let _failure = ForcedAllocationFailure::new(storage);
        let result = NormalObservation::try_angular_cone(
            provenances,
            point,
            normal,
            10.0,
            AngleUnit::Degrees,
            0.0,
            Enforcement::Hard,
        );
        assert!(matches!(
            result,
            Err(NormalObservationError::AllocationFailed { requested: 2 })
        ));
        Ok(())
    }

    #[test]
    fn angular_cone_role_allocation_failure_is_structured() -> TestResult {
        assert_angular_cone_allocation_failure(NormalObservationStorage::Roles)
    }

    #[test]
    fn angular_cone_constraint_allocation_failure_is_structured() -> TestResult {
        assert_angular_cone_allocation_failure(NormalObservationStorage::Constraints)
    }
}
